### ISSUE TITLE
Can you make it so different cool downs are different for each group

### ISSUE THREAD

**Issue by storm0chaser** [Darrionat/Command-Cooldown#1]
Can you make it so 
If your group is default
something like cool down on /feed is 2mins

if your group is vip
cooldown for /feed is 30s

**Comment by Darrionat** [comment]
Hi storm0chaser,
Thanks for the input, currently, CommandCooldown is not integrated with a permission plugin.

Could you please state what permission plugin you are using i.g. PEX, LuckPerms, etc.

There may be a feature like this implemented in the future; however, I do not plan on making it anytime soon.

**Comment by storm0chaser** [comment]
luckperms please

**Comment by Darrionat** [comment]
Stating that this feature was implemented in [update v1.8](https://www.spigotmc.org/resources/command-cooldown-1-7-1-15-support-add-cooldowns-to-commands.73696/update?update=335283). Closing this thread :)
