### ISSUE TITLE
1.18(.1) Support?

### ISSUE THREAD

**Issue by Chris6ix** [Darrionat/Command-Cooldown#10]
Hey, I really like using your plugin and would like to continue using it.
As Paper 1.18 is now "stable" I'm updating my Server soon to it, so I wanted to ask you if you could update Command Cooldown for 1.18?

Thanks,
Chris6ix

**Comment by Darrionat** [comment]
Hi Chris,

CommandCooldown should function on 1.18 with no issues. This is because CommandCooldown doesn't depend on something that was changed in the API (to my knowledge). In the future, please test before making an issue.

My best,
Darrion

**Comment by Chris6ix** [comment]
Hey Darrion, thanks for your fast response!

I didn't test any plugins yet as I plan to update my server _soon_ (haven't done anything yet) and I only went through my plugin list and looked which ones "don't officially support 1.18" to check with the devs :)

I will test this soon and get back to you with the result so that you can either update it or mark your plugin as 1.18 compatible :)

**Comment by Chris6ix** [comment]
Hey! Sorry i forgot to get back to you...
The plugin is working perfectly fine on 1.18.1, so you can add 1.18 as officially supported :)
