### ISSUE TITLE
Using version 2.5.0 but plugin thinks its 2.4.4

### ISSUE THREAD

**Issue by xX-MoonWalker-Xx** [Darrionat/Command-Cooldown#11]
Hello, i downloaded the latest version from spigot (2.5.0) and it still shows its 2.4.4 beta

If you look at the plugin jar:
![image](https://user-images.githubusercontent.com/72574462/181186845-eabca9f4-ba26-44c5-a722-5df523c61e93.png)

but in the plugin.yml:
![image](https://user-images.githubusercontent.com/72574462/181186953-57fcb125-149b-4b4c-9590-45f77833c0e3.png)

i think you guys forget to change the version or something

**Comment by Darrionat** [comment]
This will be fixed in the upcoming latest release.
