### ISSUE TITLE
Unnecessary Warnings on Startup

### ISSUE THREAD

**Issue by Chris6ix** [Darrionat/Command-Cooldown#12]
CommandCooldown throws these 3 warnings on every startup which are pretty unnecessary/useless, and I don't know of any other plugin that does the same because it's just expected behavior that the plugin can't copy (and should not copy) its default files if these already exist in the plugin folder...

So please remove these, so that the console doesn't get these unnecessary warnings all the time
![Report to CommandCooldown Dev](https://user-images.githubusercontent.com/65610536/181933524-43d35154-be15-4838-b49f-ff306f7eda66.png)

**Comment by Darrionat** [comment]
PluginLib has been updated to v1.8.2 where this issue has been fixed. This issue will be fixed in the next release of CommandCooldown.
