### ISSUE TITLE
Using latest version `2.2.0` still showing `Update Available` in Console

### ISSUE THREAD

**Issue by Zoro-6191** [Darrionat/Command-Cooldown#4]
![image](https://user-images.githubusercontent.com/52291201/124363322-27ecdf80-dc58-11eb-9546-8e0a1529e6ff.png)

![image](https://user-images.githubusercontent.com/52291201/124363356-61bde600-dc58-11eb-957f-fc70a98b54b8.png)

**Comment by Darrionat** [comment]
Hi Zoro-6191, this message should correct itself within a few hours. It states there is an update available because the SpigotMC API hasn't updated just yet. 
You can see it [here](https://api.spigotmc.org/legacy/update.php?resource=73696).
Thanks!

**Comment by Zoro-6191** [comment]
ah aight, please address that other issue I just posted
