### ISSUE TITLE
Small issue with text in `/cc help`

### ISSUE THREAD

**Issue by Zoro-6191** [Darrionat/Command-Cooldown#5]
![image](https://user-images.githubusercontent.com/52291201/124363412-b7928e00-dc58-11eb-9b83-f9f4f387e1dc.png)

![image](https://user-images.githubusercontent.com/52291201/124363418-bd886f00-dc58-11eb-8929-22c1a33475f6.png)

**Comment by Darrionat** [comment]
Great catch! I just pushed 2.2.1 to fix this. I'll post the .jar on the plugin websites.

**Comment by Zoro-6191** [comment]
cool. keep up the good work 😃
