### ISSUE TITLE
System.out/err.print Warnings

### ISSUE THREAD

**Issue by Classsic36** [Darrionat/Command-Cooldown#8]
Paper recently introduced a System.out.println catcher, which asks all plugin developers to use the plugin logger instead. More info here: https://github.com/PaperMC/Paper/pull/6278

Pastebin of warning: https://pastebin.com/EhTxcknP

This affects servers running Paper 1.17.1 Build 146 or newer. I'm currently running Command Cooldowns v2.3.5. While it doesn't really affect the plugin's functionality, I figured I would at least bring it to your attention.

**Comment by Darrionat** [comment]
Sorry for the late response. I thought I had already reviewed this. I'll perhaps change it, although it really doesn't affect Paper, plugin performance, etc. 
In short, maybe in the future.
Best, Darrion
