### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Jcodeerd** [Darrionat/Command-Cooldown#9]
how can I make it that not everyone in chat can see me making the commands?

**Comment by Darrionat** [comment]
Are you saying that others are able to see you performing edits to the command cooldowns?

**Comment by Jcodeerd** [comment]
yes, they can see that I put "1d" etc in chat

**Comment by Darrionat** [comment]
Oh okay, I see what you mean. 
What version of the plugin do you have, and what server version are you using? 

Thank you,
Darrion

**Comment by Jcodeerd** [comment]
the latest one, and airplane 1.17.1

btw I removed the plugin since it was too inconvinient for me

>
